[project]
name = "hello-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=1.2.3",
    "langchain-ollama>=1.0.1",
    "langchain-openai>=1.1.7",
]
