[project]
name = "aws-hello-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.26",
    "langchain>=1.2.3",
    "langchain-aws>=1.2.0",
]
